---
abstract: "access to the Perl interpreter's argv"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Devel::PL_origargv
name: Devel-PL_origargv
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Inline::C: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Devel-PL_origargv
  homepage: https://metacpan.org/release/Devel-PL_origargv
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-devel-pl_origargv
version: 0.002
